### PR TITLE
[RFC] Making headers clearer and adding search words

### PR DESCRIPTION
**Pull request by rgoliveira**
What do you guys think? I thought the abbreviated headers should be clearer, so anyone can understand them at first glance. To facilitate search inside the page, I added some keywords where it made sense.

Still need to:
- [x] review and fix TOC links

### CODE REVIEW

**Comment by Navrin** [comment]
(Note that the current c# header link and c++ link are broken because the `#` symbol and `+` are stripped out when making the header IDs.)

**Comment by rgoliveira** [comment]
Nice catch. I was meaning to fix those after generating the page and checking the generated anchors, just forgot to mention it here. Will edit my first message.

**Comment by lethargilistic** [comment]
I like this.

**Comment by rgoliveira** [comment]
Ok, I'm going to merge this, then fix and merge #16, and will probably need fix the TOC after

**Pull request merged**
